data class Post(
    val id: Int = 0,
    val ownerId: Int = 0,
    val fromId: Int?,
    val created_by: Int?,
    val date: Int?,
    val text: String?,
    val reply_owner_id: Int?,
    val reply_post_id: Int?,
    val copyright : CopyRight?,
    val likes : Likes?,
    val reposts : Repost?,
    val views : Views?,
    val friendsOnly: Boolean = false,
    val comments: Comment? ,
    val postType: String = "post",
    val geo: Geo?,
    val signerId: Int?,
    val canPin: Boolean = true,
    val canDelete: Boolean = true,
    val canEdit: Boolean = true,
    val isPinned: Boolean = false,
    val marked_as_ads: Boolean?,
    val is_favorite: Boolean?,
    val postponed_id: Int?
)